### ISSUE TITLE
Problem with building it on Ubuntu

### ISSUE THREAD

**Issue by varosi** [stepcut/idris-blink#3]
I do "make" then I get errors that I cannot find why. Could you help me?

> board-mega2560.mk Configuration:
> - [AUTODETECTED]       CURRENT_OS = LINUX 
> - [AUTODETECTED]       ARDUINO_DIR = /usr/share/arduino 
> - [AUTODETECTED]       PYTHON_CMD = /usr/bin/python3 
> - [COMPUTED]           ARDMK_DIR = /home/varosi/idris/idris-blink/arduino-makefile (relative to Common.mk)
> - [AUTODETECTED]       ARDUINO_VERSION = 105 
> - [DEFAULT]            ARCHITECTURE =  
> - [DEFAULT]            ARDMK_VENDOR = arduino 
> - [DEFAULT]            ARDUINO_SKETCHBOOK =  
> - [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino//variants (from ARDUINO_DIR)
> - [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino//boards.txt (from ARDUINO_DIR)
> - [USER]               AVR_TOOLS_DIR = /usr 
> - [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
> - [DEFAULT]            USER_LIB_PATH = /libraries (in user sketchbook)
> - [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh 
> - [USER]               BOARD_SUB = atmega2560 
> - [USER]               BOARD_TAG = mega 
> - [COMPUTED]           CORE = arduino (from build.core)
> - [COMPUTED]           VARIANT = mega (from build.variant)
> - [COMPUTED]           BOARD = _MEGA (from build.board)
> - [COMPUTED]           OBJDIR = build-mega-atmega2560 (from BOARD_TAG)
> - [COMPUTED]           ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino//cores/arduino (from ARDUIN
> O_DIR, BOARD_TAG and boards.txt)
> - [COMPUTED]           RESET_CMD = /usr/bin/python3 /home/varosi/idris/idris-blink/arduino-makefile/bin/ar
> d-reset-arduino   (from PYTHON_CMD, ARD_RESET_OPTS and MONITOR_PORT)
> -                      No .pde or .ino files found. If you are compiling .c or .cpp files then you need to
>  explicitly include Arduino header files
> - [MANUAL]             NO_CORE_MAIN_CPP set so core library will not include main.cpp
> - [ASSUMED]            MONITOR_BAUDRATE = 9600 
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> - [DEFAULT]            OPTIMIZATION_LEVEL = s 
> - [DEFAULT]            MCU_FLAG_NAME = mmcu 
> - [DEFAULT]            CFLAGS_STD = -std=gnu11 
> - [DEFAULT]            CXXFLAGS_STD = -std=gnu++11 
> - [AUTODETECTED]       DEVICE_PATH =  
> - [DEFAULT]            FORCE_MONITOR_PORT =  
> - [AUTODETECTED]       Size utility: AVR-aware for enhanced output
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> - [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino//bootloaders (from ARDUINO_
> DIR)
> - [COMPUTED]           ARDMK_VERSION = 1.6 
> - [COMPUTED]           CC_VERSION = 5.4.0 (avr-gcc)
> -------------------------
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> sed: can't read build/exec/Blink.c: No such file or directory
> mkdir -p build-mega-atmega2560
> rm -f "build/exec/Blink.c"
> CC=true idris2 --codegen refc "Blink.idr" <<< ":compile Blink main"
> /bin/sh: 1: Syntax error: redirection unexpected
> make: *** [aux-makefiles/Idris2.mk:27: build/exec/Blink.c] Error 2

**Comment by buzden** [comment]
Oh, sorry, I didn't know that some shells do not have `<<<` redirection. I tried to fix this at commit 6c85dee0d5854554525086bff2139cf8a34e79e0, please check whether this works for you.

**Comment by varosi** [comment]
Wow! Nice! Thanks for the fast answer and fix! It's seems to work now!
